import '../styles/leaflet.css'
import "../styles/globals.css";

import Head from "next/head";
import PageLayout from "../components/PageLayout";

import { ThemeProvider } from 'next-themes'

import type { AppProps } from "next/app";

function MyApp({ Component, pageProps }: AppProps) {
	if (process.env.NODE_ENV === 'production') console.warn = function () { };
	return (
		<>
			<ThemeProvider attribute="class">
				<Head>
					<title>AreaGraph v2</title>
					<meta name="description" content="Generated by create-t3-app" />
					<link rel="icon" href="/favicon.ico" />
				</Head>

				<PageLayout><Component {...pageProps} /></PageLayout>
			</ThemeProvider>

		</>
	);
}

export default MyApp;


export const getBaseUrl = () => {
	if (typeof window !== "undefined") {
		return "";
	}
	if (process.browser) return "";
	if (process.env.VERCEL_URL) return `https://${process.env.VERCEL_URL}`;

	return `http://localhost:${process.env.PORT ?? 3000}`;
};
